SELECT * FROM customer

-- Q1. What is the total revenue generated by male vs. female customers?
SELECT gender, SUM(purchase_amount) AS revenue
FROM customer
GROUP BY gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount?
SELECT customer_id, purchase_amount
FROM customer
WHERE discount_applied ='YES'
AND purchase_amount > (SELECT AVG(purchase_amount) FROM customer);

-- Q3. Which are the top 5 products with the highest average review rating?
SELECT TOP 5 WITH TIES item_purchased,ROUND(AVG(review_rating),3) AS [average_product_rating]
FROM customer
GROUP BY item_purchased
ORDER BY average_product_rating DESC;

-- Q4. Compare the average Purchase amounts beween Standard and Express Shipping?
SELECT shipping_type, CAST(AVG(purchase_amount * 1.0) AS decimal(10,2)) AS [average_purchase_amount]
FROM customer
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
SELECT subscription_status, COUNT(customer_id) AS [total_customers], CAST(AVG(purchase_amount * 1.0)AS decimal(10,2)) AS [average_spend], SUM(purchase_amount) AS [total_revenue]
FROM customer
GROUP BY subscription_status;

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT TOP 5 item_purchased, CAST(SUM(CASE WHEN discount_applied ='YES' THEN 1 ELSE 0 END) * 100.0/COUNT(*) AS decimal(10,2)) AS [purchase_percentage]
FROM customer
GROUP BY item_purchased
ORDER BY purchase_percentage DESC;

--Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment. 
WITH customer_type AS
(
	SELECT customer_id,
	CASE WHEN previous_purchases = 1 THEN 'New'
	WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
	ELSE 'Loyal' END AS customer_segment
	FROM customer
)
SELECT customer_segment, COUNT(*) AS [number_of_customers]
FROM customer_type
GROUP BY customer_segment;


--Q8. What are the top 3 most purchased products within each category? 
SELECT category, item_purchased, COUNT(item_purchased) AS [times_purchased]
FROM customer AS [a]
WHERE item_purchased IN (SELECT TOP 3 item_purchased FROM customer WHERE category = a.category GROUP BY item_purchased ORDER BY COUNT(*) DESC)
GROUP BY category, item_purchased
ORDER BY category, times_purchased DESC;


--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status, COUNT(customer_id) AS [repeat_buyers]
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;


--Q10. What is the revenue contribution of each age group? 
SELECT age_group, CAST(SUM(purchase_amount) * 100.0/ (SELECT SUM(purchase_amount) FROM customer) AS decimal(10,2)) AS [revenue_contribution]
FROM customer
GROUP BY age_group
ORDER BY revenue_contribution DESC;